### PR TITLE
Basic block program logic

### PR DESCRIPTION
**Pull request by seed**
This adds basic block program logic described in the paper "Towards Verifying Ethereum Smart Contract
Bytecode in Isabelle/HOL" published at CPP'18 and available at https://github.com/seed/ethbbl.

The logic facilitate formal reasoning about bytecode by structuring bytecode sequences
into blocks of straight-line code.
We proved the logic sound and have used it to formally verify the functional correctness of an escrow agreement smart contract implemented in Solidity.

### CODE REVIEW

**Comment by seed** [comment]
We are working on getting SimpleWallet working again.

**Comment by seed** [comment]
@pirapira I just ran `make lem-thy && make simplewallet' successfully.
Do you have any advice to trouble shoot such discrepancy?

**Comment by pirapira** [comment]
@seed something similar happened to me a while ago.  Isabelle2017 in Travis behaved differently from one on my local machine.  I think I should check this branch on my machine and then merge the PR.

**Comment by pirapira** [comment]
Somehow on my local machine I see this

```
simplewallet FAILED
(see also /home/yh/.isabelle/Isabelle2017/heaps/polyml-5.6_x86-linux/log/simplewallet)
###                  (if meter_gas i v ?c1 ?net1 \<le> vctx_gas v then []
###                   else [OutOfGas])))
###             v None
### | InstructionToEnvironment x xa xb \<Rightarrow> ?pr1.1
### Ignoring duplicate rewrite rule:
### memory_as_set ?m \<equiv> {MemoryElm (a, v) |a v. ?m a = v}
### Ignoring duplicate rewrite rule:
### storage_as_set ?s \<equiv> {StorageElm (i, v) |i v. ?s i = v}
### Ignoring duplicate rewrite rule:
### log_as_set ?logs \<equiv>
### {LogNumElm (length ?logs)} \<union>
### {LogElm (pos, l) |pos l. rev ?logs ! pos = l \<and> pos < length ?logs}
### Ignoring duplicate rewrite rule:
### balance_as_set ?b \<equiv> {BalanceElm (a, v) |a v. ?b a = v}
### Ignoring duplicate rewrite rule:
### next_state ?stopper1 ?c1 ?net1 ?pr1.1 \<equiv>
### case ?pr1.1 of
### InstructionContinue v \<Rightarrow>
###   case vctx_next_instruction v ?c1 of
###   None \<Rightarrow>
###     InstructionToEnvironment (ContractFail [ShouldNotHappen]) v None
###   | Some i \<Rightarrow>
###       if check_resources v ?c1 (vctx_stack v) i ?net1
###       then instruction_sem v ?c1 i ?net1
###       else InstructionToEnvironment
###             (ContractFail
###               (case inst_stack_numbers i of
###                (consumed, produced) \<Rightarrow>
###                  (if int (length (vctx_stack v)) + produced - consumed
###                      \<le> 1024
###                   then [] else [TooLongStack]) @
###                  (if meter_gas i v ?c1 ?net1 \<le> vctx_gas v then []
###                   else [OutOfGas])))
###             v None
### | InstructionToEnvironment x xa xb \<Rightarrow> ?pr1.1
isabelle document -o 'pdf' -n 'document' -t '' simplewallet/document 2>&1
*** /home/yh/infra-src/Isabelle2017/lib/Tools/latex: line 74: pdflatex: command not found
*** Document preparation failure in directory 'simplewallet/document'
*** 
*** Failed to build document "/home/yh/src/eth-isabelle/simplewallet/document.pdf"
Unfinished session(s): simplewallet
```

**Comment by pirapira** [comment]
(sorry, my previous message was about `pdflatex` missing).

**Comment by pirapira** [comment]
Thank you very much!

**Pull request merged**
